/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera } from "@react-three/drei";

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/rCCkg9OaPHQWHEmY/scene.splinecode"
  );
  return (
    <>
      <color attach="background" args={["#fefefe"]} />
      <group {...props} dispose={null}>
        <group name="Cube Clones" position={[0, 90, 0]}>
          <group name="Clone 0" position={[-52, -52, -52]}>
            <mesh
              name="Cube"
              geometry={nodes.Cube.geometry}
              material={materials["segment-bright"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 1" position={[-52, -52, 0]}>
            <mesh
              name="Cube1"
              geometry={nodes.Cube1.geometry}
              material={materials["segment-dark"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 2" position={[-52, -52, 52]}>
            <mesh
              name="Cube2"
              geometry={nodes.Cube2.geometry}
              material={materials["segment-bright"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 3" position={[-52, 0, -52]}>
            <mesh
              name="Cube3"
              geometry={nodes.Cube3.geometry}
              material={materials["segment-dark"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 4" position={[-52, 0, 0]}>
            <mesh
              name="Cube4"
              geometry={nodes.Cube4.geometry}
              material={materials["segment-bright"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 5" position={[-52, 0, 52]}>
            <mesh
              name="Cube5"
              geometry={nodes.Cube5.geometry}
              material={materials["segment-dark"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 6" position={[-52, 52, -52]}>
            <mesh
              name="Cube6"
              geometry={nodes.Cube6.geometry}
              material={materials["segment-bright"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 7" position={[-52, 52, 0]}>
            <mesh
              name="Cube7"
              geometry={nodes.Cube7.geometry}
              material={materials["segment-dark"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 8" position={[-52, 52, 52]}>
            <mesh
              name="Cube8"
              geometry={nodes.Cube8.geometry}
              material={materials["segment-bright"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 9" position={[0, -52, -52]}>
            <mesh
              name="Cube9"
              geometry={nodes.Cube9.geometry}
              material={materials["segment-dark"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 10" position={[0, -52, 0]}>
            <mesh
              name="Cube10"
              geometry={nodes.Cube10.geometry}
              material={materials["segment-dark"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 11" position={[0, -52, 52]}>
            <mesh
              name="Cube11"
              geometry={nodes.Cube11.geometry}
              material={materials["segment-dark"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 12" position={[0, 0, -52]}>
            <mesh
              name="Cube12"
              geometry={nodes.Cube12.geometry}
              material={materials["segment-bright"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 13">
            <mesh
              name="Cube13"
              geometry={nodes.Cube13.geometry}
              material={materials["segment-dark"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 14" position={[0, 0, 52]}>
            <mesh
              name="Cube14"
              geometry={nodes.Cube14.geometry}
              material={materials["segment-dark"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 15" position={[0, 52, -52]}>
            <mesh
              name="Cube15"
              geometry={nodes.Cube15.geometry}
              material={materials["segment-dark"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 16" position={[0, 52, 0]}>
            <mesh
              name="Cube16"
              geometry={nodes.Cube16.geometry}
              material={materials["segment-dark"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 17" position={[0, 52, 52]}>
            <mesh
              name="Cube17"
              geometry={nodes.Cube17.geometry}
              material={materials["segment-bright"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 18" position={[52, -52, -52]}>
            <mesh
              name="Cube18"
              geometry={nodes.Cube18.geometry}
              material={materials["segment-bright"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 19" position={[52, -52, 0]}>
            <mesh
              name="Cube19"
              geometry={nodes.Cube19.geometry}
              material={materials["segment-dark"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 20" position={[52, -52, 52]}>
            <mesh
              name="Cube20"
              geometry={nodes.Cube20.geometry}
              material={materials["segment-bright"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 21" position={[52, 0, -52]}>
            <mesh
              name="Cube21"
              geometry={nodes.Cube21.geometry}
              material={materials["segment-dark"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 22" position={[52, 0, 0]}>
            <mesh
              name="Cube22"
              geometry={nodes.Cube22.geometry}
              material={materials["segment-bright"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 23" position={[52, -1, 52]}>
            <mesh
              name="Cube23"
              geometry={nodes.Cube23.geometry}
              material={materials["segment-dark"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 24" position={[52, 52, -52]}>
            <mesh
              name="Cube24"
              geometry={nodes.Cube24.geometry}
              material={materials["segment-dark"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 25" position={[52, 52, 52.59]}>
            <mesh
              name="Cube25"
              geometry={nodes.Cube25.geometry}
              material={materials["segment-bright"]}
              castShadow
              receiveShadow
            />
          </group>
          <group name="Clone 26" position={[52, 52, 52.92]}>
            <mesh
              name="Cube26"
              geometry={nodes.Cube26.geometry}
              material={materials["segment-dark"]}
              castShadow
              receiveShadow
              position={[0, 0, -53.18]}
            />
          </group>
        </group>
        <group name="Cube27" position={[0, 90, 0]}>
          <mesh
            name="Cube28"
            geometry={nodes.Cube28.geometry}
            material={materials["segment-dark"]}
            castShadow
            receiveShadow
          />
        </group>
        <mesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials["Plane Material"]}
          castShadow
          receiveShadow
          position={[2, 1, 1]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        />
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={4.87}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-231.2685}
          shadow-camera-right={231.2685}
          shadow-camera-top={231.2685}
          shadow-camera-bottom={-231.2685}
          position={[-159.94, 579.98, 1443.34]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-1, 1, 1.81]}
        />
        <OrthographicCamera
          name="1"
          makeDefault={true}
          zoom={2.52}
          far={100000}
          near={-100000}
          position={[-79.91, 229.87, 1107.73]}
          rotation={[-0.13, -0.05, -0.01]}
        />
        <hemisphereLight
          name="Default Ambient Light"
          intensity={0.75}
          color="#eaeaea"
        />
      </group>
    </>
  );
}
